name: LlamaCppAndroidTest Build

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          repository: ag2s20150909/LlamaCppAndroidTest
          fetch-depth: 1
      - name: clone repo
        uses: actions/checkout@v4
        with:
          repository: ggerganov/llama.cpp
          path: './llama/src/main/cpp'
          fetch-depth: 1
      - name: clone repo
        uses: actions/checkout@v4
        with:
          path: './repo'
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt-hotspot'
          java-version: 17
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Apk Sign
        run: |
          echo "给apk增加签名"
          cp ./repo/.github/workflows/easy-to-build.jks ./android/easy-to-build.jks
          sed '$a\RELEASE_STORE_FILE=./easy-to-build.jks'               ./gradle.properties -i
          sed '$a\RELEASE_KEY_ALIAS=easy-to-build'                      ./gradle.properties -i
          sed '$a\RELEASE_STORE_PASSWORD=easy-to-build'                 ./gradle.properties -i
          sed '$a\RELEASE_KEY_PASSWORD=easy-to-build'          ./android/res/values/strings.xml -i

      - name: Build With Gradle
        continue-on-error: true
        run: |
          echo "开始构建"
          chmod +x gradlew
          ./gradlew build --build-cache --parallel --no-daemon --warning-mode all

      - name: move apk
        run: |
          echo "修改APK文件名"
          mkdir -p ${{ github.workspace }}/apk/
          for file in `ls ${{ github.workspace }}/android/*/*/*/*/*.apk`; do
            mv "$file" ${{ github.workspace }}/apk/LlamaCppAndroidTest.apk
          done

      - name: Check Build production
        run: |
          cd ${{ github.workspace }}/apk/
          if [ ! -e LlamaCppAndroidTest.apk ]; then
            echo "Build production not found! Check gradle logs."
            exit 1
          fi

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LlamaCppAndroidTest
          if-no-files-found: ignore
          path: ${{ github.workspace }}/apk/*.apk
