name: LlamaCppAndroidTest Build

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          repository: ag2s20150909/LlamaCppAndroidTest
          fetch-depth: 1
      - name: clone repo
        uses: actions/checkout@v4
        with:
          repository: ggerganov/llama.cpp
          path: './llama/src/main/cpp/llama.cpp'
          fetch-depth: 1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: patch
        run: |
          echo "移除朗读"
          sed "s/say(it.messages.last().content,context)//" ./app/src/main/java/me/ag2s/app/MainViewModel.kt -i

      - name: Build With Gradle
        continue-on-error: true
        run: |
          echo "开始构建"
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --no-daemon --warning-mode all

      - name: move apk
        run: |
          echo "修改APK文件名"
          mkdir -p ${{ github.workspace }}/apk/
          ls ${{ github.workspace }}/app/*/*/*/*/*.apk
          for file in `ls ${{ github.workspace }}/app/*/*/*/*/*.apk`; do
            mv "$file" ${{ github.workspace }}/apk/LlamaCppAndroidTest.apk
          done

      - name: Check Build production
        run: |
          cd ${{ github.workspace }}/apk/
          if [ ! -e LlamaCppAndroidTest.apk ]; then
            echo "Build production not found! Check gradle logs."
            exit 1
          fi

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LlamaCppAndroidTest
          if-no-files-found: ignore
          path: ${{ github.workspace }}/apk/*.apk
